from enum import StrEnum


class Severidad(StrEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"


class CodigoError(StrEnum):
    UNKNOWN = "UNKNOWN"
    CONFIG_INVALIDA = "CONFIG_INVALIDA"
    RECURSO_CERRADO = "RECURSO_CERRADO"
    SESION_OCUPADA = "SESION_OCUPADA"
    SESION_LEASE_PERDIDO = "SESION_LEASE_PERDIDO"
    SESION_RECUPERACION_REQUERIDA = "SESION_RECUPERACION_REQUERIDA"
    SESION_INVALIDA = "SESION_INVALIDA"
    SESION_STORE_FALLO = "SESION_STORE_FALLO"
