from enum import StrEnum


class Severidad(StrEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"


class CodigoError(StrEnum):
    UNKNOWN = "UNKNOWN"
    CONFIG_INVALIDA = "CONFIG_INVALIDA"
    RECURSO_CERRADO = "RECURSO_CERRADO"
    RUNTIME_CIERRE_TIMEOUT = "RUNTIME_CIERRE_TIMEOUT"
    PROVIDER_FALLO = "PROVIDER_FALLO"
    PROVIDER_TIMEOUT = "PROVIDER_TIMEOUT"
    PROVIDER_RESPUESTA_INVALIDA = "PROVIDER_RESPUESTA_INVALIDA"
    TOOL_NO_ENCONTRADA = "TOOL_NO_ENCONTRADA"
    TOOL_ARGUMENTOS_INVALIDOS = "TOOL_ARGUMENTOS_INVALIDOS"
    TOOL_TIMEOUT = "TOOL_TIMEOUT"
    TOOL_FALLO = "TOOL_FALLO"
    TOOL_OMITIDA_POR_LIMITE = "TOOL_OMITIDA_POR_LIMITE"
    TOOL_RESULTADO_INVALIDO = "TOOL_RESULTADO_INVALIDO"
    FINAL_ANSWER_INVALIDA = "FINAL_ANSWER_INVALIDA"
    HOOK_FALLO = "HOOK_FALLO"
    HISTORIAL_TRANSFORM_INVALIDO = "HISTORIAL_TRANSFORM_INVALIDO"
    SESION_OCUPADA = "SESION_OCUPADA"
    SESION_LEASE_PERDIDO = "SESION_LEASE_PERDIDO"
    SESION_CONFLICTO = "SESION_CONFLICTO"
    SESION_ENGINE_DISTINTO = "SESION_ENGINE_DISTINTO"
    SESION_RECUPERACION_REQUERIDA = "SESION_RECUPERACION_REQUERIDA"
    SESION_INVALIDA = "SESION_INVALIDA"
    SESION_STORE_FALLO = "SESION_STORE_FALLO"

